// import { Reservation } from "./datatable";

// export const data: Reservation[] = [
//   {
//     id: "LG-B00108",
//     guestName: "Angus Copper",
//     roomType: "Deluxe",
//     roomNumber: "101",
//     request: "Late Check-Out",
//     duration: 3,
//     checkIn: "June 19, 2028",
//     checkOut: "June 22, 2028",
//     status: "Confirmed",
//   },
//   {
//     id: "LG-B00109",
//     guestName: "Catherine Lopp",
//     roomType: "Standard",
//     roomNumber: "202",
//     request: "None",
//     duration: 2,
//     checkIn: "June 19, 2028",
//     checkOut: "June 21, 2028",
//     status: "Confirmed",
//   },
//   {
//     id: "LG-B00110",
//     guestName: "Edgar Irving",
//     roomType: "Suite",
//     roomNumber: "303",
//     request: "Extra Pillows",
//     duration: 5,
//     checkIn: "June 19, 2028",
//     checkOut: "June 24, 2028",
//     status: "Pending",
//   },
//   {
//     id: "LG-B00111",
//     guestName: "Gertrude Bale",
//     roomType: "Standard",
//     roomNumber: "204",
//     request: "Early Check-In",
//     duration: 1,
//     checkIn: "June 19, 2028",
//     checkOut: "June 20, 2028",
//     status: "Confirmed",
//   },
//   {
//     id: "LG-B00112",
//     guestName: "Ice B. Holand",
//     roomType: "Deluxe",
//     roomNumber: "105",
//     request: "Airport Pickup",
//     duration: 4,
//     checkIn: "June 19, 2028",
//     checkOut: "June 23, 2028",
//     status: "Pending",
//   },
// ];